org_suffixes_dict = {
    'limited liability partnership': 'llp',
    ' limited liability partnership': 'llp',
    ' limited liability partnership ': 'llp',
    'public limited company': 'plc',
    ' public limited company': 'plc',
    ' public limited company ': 'plc',
    'limited' : 'ltd',
    ' limited ' : 'ltd',
    ' limited': 'ltd',
    'l.l.p' : 'llp',
    ' l.l.p' : 'llp',
    ' l.l.p ' : 'llp',
    'l l p': 'llp',
    ' l l p': 'llp',
    ' l l p ': 'llp',
    ' nhs ft' : 'nft',
    ' nhs ft ' : 'nft',
    'nhs ft' : 'nft',
    'nhs trust' : 'nft',
    ' nhs trust ' : 'nft',
    ' nhs trust' : 'nft',
    'nhs foundation trust' : 'nft',
    ' nhs foundation trust ' : 'nft',
    ' nhs foundation trust' : 'nft',
    'n f t' : 'nft',
    ' n f t ' : 'nft',
    ' n f t' : 'nft',
    }



#
# org_suffixes_dict = {
#     'limited' : 'ltd',
#     ' limited ' : 'ltd',
#     ' limited': 'ltd',
#     'limited liability partnership': 'llp',
#     ' limited liability partnership': 'llp',
#     ' limited liability partnership ': 'llp',
#     'l.l.p' : 'llp',
#     ' l.l.p' : 'llp',
#     ' l.l.p ' : 'llp',
#     'l l p': 'llp',
#     ' l l p': 'llp',
#     ' l l p ': 'llp',
#     'registry limited company' : 'plc',
#     ' registry limited company' : 'plc',
#     ' registry limited company ' : 'plc',
#
#     }
